export const alcoholCategoryMappedKorean = {
    // 기본 베이스 주류
    "보드카": "Vodka",
    "진": "Gin",
    "럼": "Rum",
    "화이트 럼": "White rum",
    "다크 럼": "Dark rum",
    "골드 럼": "Gold rum",
    "위스키": "Whiskey",
    "스카치 위스키": "Scotch whiskey",
    "아이리시 위스키": "Irish whiskey",
    "버번 위스키": "Bourbon whiskey",
    "라이 위스키": "Rye whiskey",
    "테킬라": "Tequila",
    "실버 테킬라": "Silver tequila",
    "골드 테킬라": "Gold tequila",
    "메즈칼": "Mezcal",
    "브랜디": "Brandy",
    "코냑": "Cognac",
    "아르마냑": "Armagnac",
  
    // 리큐어
    "커피 리큐르": "Coffee liqueur",
    "깔루아": "Kahlua",
    "오렌지 리큐르": "Orange liqueur",
    "블루 큐라소": "Blue Curacao",
    "트리플 섹": "Triple sec",
    "캄파리": "Campari",
    "아마레토": "Amaretto",
    "멜론 리큐르": "Melon liqueur",
    "체리 리큐르": "Cherry liqueur",
    "애프리코트 브랜디": "Apricot brandy",
    "피치 슈냅스": "Peach schnapps",
    "애플 리큐르": "Apple liqueur",
    "크림 드 카카오": "Crème de cacao",
    "크림 드 민트": "Crème de menthe",
    "크랜베리 리큐르": "Cranberry liqueur",
    "민트 리큐르": "Mint liqueur",
    "갈리아노": "Galliano",
    "그랑 마니에르": "Grand Marnier",
    "퍼넬": "Fernet",
    "아페롤": "Aperol",
    "바나나 리큐르": "Banana liqueur",
    "카시스 리큐르": "Crème de cassis",
    "아니스 리큐르": "Anise liqueur",
    "베일리스": "Baileys Irish Cream",
    "드람뷔": "Drambuie",
  
    // 와인 및 스파클링
    "레드 와인": "Red wine",
    "화이트 와인": "White wine",
    "스파클링 와인": "Sparkling wine",
    "샴페인": "Champagne",
    "포트 와인": "Port wine",
    "셰리": "Sherry",
    "마데이라": "Madeira",
    "베르무트": "Vermouth",
    "드라이 베르무트": "Dry vermouth",
    "스위트 베르무트": "Sweet vermouth",
    
    // 맥주
    "라거 맥주": "Lager beer",
    "에일 맥주": "Ale beer",
    "스타우트 맥주": "Stout beer",
    "IPA": "IPA",
  
    // 증류주 및 기타
    "코코넛 럼": "Coconut rum",
    "바닐라 럼": "Vanilla rum",
    "꿀": "Honey",
  
    // 기타
    "커피": "Coffee",
    "크림": "Cream",
    "버터스코치 슈냅스": "Butterscotch schnapps",
    "체리 브랜디": "Cherry brandy",
    "핑크 와인": "Rosé wine",
    "피스코": "Pisco",
    "칵테일 비터스": "Cocktail bitters",
    "앙고스투라 비터스": "Angostura bitters",
    "초콜릿 리큐르": "Chocolate liqueur",
    "진저 리큐르": "Ginger liqueur",
    "엘더플라워 리큐르": "Elderflower liqueur",
    "팔레르모 리큐르": "Palerma liqueur",
    "코코넛 크림": "Coconut cream",
    "헤이즐넛 리큐르": "Hazelnut liqueur",
    "마라스키노 체리 리큐르": "Maraschino cherry liqueur",
    "화이트 초콜릿 리큐르": "White chocolate liqueur",
};
